<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VoiceCore\VoiceCore.csproj" />
    <ProjectReference Include="..\VoiceCore.Synthetic\VoiceCore.Synthetic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VoiceCore.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
