// <auto-generated>
// Written by `VoiceCore.Batch corpus calibrate` (spec §3.9, build step 5). Don't edit by hand:
// refit, then bump AnalysisConfig.AnalyzerVersion so PBs never compare across calibrations.
// fit 2026-10-01 on the dev split of corpus abfd736e2ec71dea: 56 files, 14 speakers (56 public)
// raw scores from analyzer 0.2.0; judged frames: f0 7763, Silence 23003, Unvoiced 7505, Voiced 8914, Creak 0
// reference (56 files): PTDB-TUG laryngograph reference, RAPT (Snack ESPS), 32 ms window, 10 ms hop
// </auto-generated>

#nullable enable

namespace VoiceCore;

internal static class FittedCalibration
{
    public static readonly ConfidenceCalibrationTable? Table = new()
    {
        Name = "corpus-20261001-abfd736e",
        F0 = new CalibrationMap(
            [8.85884E-06f, 0.03816613f, 0.08222221f, 0.15557449f, 0.22823265f, 0.37086743f, 0.6265744f, 0.7886834f, 0.8563544f, 0.9101845f, 0.9644237f],
            [0.6377551f, 0.8367347f, 0.89285713f, 0.93367344f, 0.9606164f, 0.97300774f, 0.98382354f, 0.98717946f, 0.9907407f, 0.99657536f, 0.9995714f]),
        Silence = new CalibrationMap(
            [0.7267841f, 0.8603617f, 0.93409455f],
            [0.99095863f, 0.9938057f, 0.99478763f]),
        Unvoiced = new CalibrationMap(
            [0.54942614f, 0.66295314f, 0.7067501f, 0.7240675f, 0.7727221f, 0.8118168f, 0.82804227f, 0.9090368f],
            [0.6673729f, 0.77701f, 0.91534394f, 0.9255319f, 0.95729536f, 0.95767194f, 0.9680851f, 0.9716689f]),
        Voiced = new CalibrationMap(
            [0.5f, 0.53133017f, 0.6315144f, 0.7126192f, 0.74227387f, 0.7602143f, 0.77733946f, 0.84194833f, 0.8971223f, 0.9107028f, 0.9237102f, 0.96312535f],
            [0.5810502f, 0.76233184f, 0.81294966f, 0.8295964f, 0.86160713f, 0.875f, 0.8839286f, 0.916f, 0.92410713f, 0.9349776f, 0.9375f, 0.9650883f]),
        Creak = null,  // no reference in the corpus can judge Creak frames yet: raw score
    };
}
