using System.Globalization;
using System.Text;

namespace VoiceCore.Batch.Corpus;

/// <summary>
/// Fits the §3.9 confidence calibration: a monotone map from raw score to the
/// observed rate of being right, by binned isotonic regression on the dev split.
/// </summary>
internal static class CalibrationFit
{
    /// <summary>Fewer judged frames than this and a map isn't fit (the confidence stays raw).</summary>
    public const int MinSamples = 200;

    /// <summary>
    /// Pre-bins sorted scores into groups of at least <paramref name="minBin"/> frames
    /// (never splitting equal scores), then pools adjacent violators (PAV) until the
    /// rates are non-decreasing. Each pooled block becomes one knot at its mean raw
    /// score, with a Laplace-smoothed rate so no knot claims exactly 0 or 1.
    /// </summary>
    public static CalibrationMap? Fit(IReadOnlyList<(float Raw, bool Correct)> samples, int minBin = 50)
    {
        if (samples.Count < MinSamples)
            return null;
        var sorted = samples.Where(s => float.IsFinite(s.Raw)).OrderBy(s => s.Raw).ToArray();
        int binSize = Math.Max(minBin, sorted.Length / 40);

        // pre-binning: contiguous runs of ≥ binSize, never splitting a run of equal scores
        var bins = new List<Block>();
        var current = new Block();
        for (int i = 0; i < sorted.Length; i++)
        {
            current.Add(sorted[i].Raw, sorted[i].Correct);
            bool atomEnds = i + 1 == sorted.Length || sorted[i + 1].Raw != sorted[i].Raw;
            if (atomEnds && current.N >= binSize)
            {
                bins.Add(current);
                current = new Block();
            }
        }
        if (current.N > 0)
        {
            if (bins.Count > 0 && current.N < binSize / 2)
                bins[^1].Merge(current);
            else
                bins.Add(current);
        }

        // pool adjacent violators
        var blocks = new List<Block>();
        foreach (var bin in bins)
        {
            blocks.Add(bin);
            while (blocks.Count > 1 && blocks[^2].Rate >= blocks[^1].Rate)
            {
                blocks[^2].Merge(blocks[^1]);
                blocks.RemoveAt(blocks.Count - 1);
            }
        }

        var raw = new float[blocks.Count];
        var probability = new float[blocks.Count];
        for (int k = 0; k < blocks.Count; k++)
        {
            raw[k] = (float)(blocks[k].SumRaw / blocks[k].N);
            float p = (float)((blocks[k].Correct + 1.0) / (blocks[k].N + 2.0));
            probability[k] = k > 0 ? Math.Max(p, probability[k - 1]) : p;  // smoothing can't undo monotonicity
        }
        return new CalibrationMap(raw, probability);
    }

    private sealed class Block
    {
        public long N;
        public long Correct;
        public double SumRaw;
        public double Rate => (double)Correct / N;

        public void Add(float raw, bool correct)
        {
            N++;
            SumRaw += raw;
            if (correct)
                Correct++;
        }

        public void Merge(Block other)
        {
            N += other.N;
            Correct += other.Correct;
            SumRaw += other.SumRaw;
        }
    }

    /// <summary>The generated VoiceCore/FittedCalibration.cs: the table as reviewable source.</summary>
    public static string GenerateSource(ConfidenceCalibrationTable table, IEnumerable<string> provenance)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Written by `VoiceCore.Batch corpus calibrate` (spec §3.9, build step 5). Don't edit by hand:");
        sb.AppendLine("// refit, then bump AnalysisConfig.AnalyzerVersion so PBs never compare across calibrations.");
        foreach (string line in provenance)
            sb.AppendLine("// " + line);
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace VoiceCore;");
        sb.AppendLine();
        sb.AppendLine("internal static class FittedCalibration");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly ConfidenceCalibrationTable? Table = new()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Name = \"{table.Name}\",");
        sb.AppendLine($"        F0 = {Map(table.F0)},");
        foreach (var state in new[] { VoicingState.Silence, VoicingState.Unvoiced, VoicingState.Voiced, VoicingState.Creak })
            sb.AppendLine(table.VoicingFor(state) is { } map
                ? $"        {state} = {Map(map)},"
                : $"        {state} = null,  // no reference in the corpus can judge {state} frames yet: raw score");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Map(CalibrationMap map)
    {
        // round-trip formatting: rounding could make two knots equal
        string Floats(IReadOnlyList<float> v) => string.Join(", ", v.Select(x => x.ToString("R", CultureInfo.InvariantCulture) + "f"));
        return $"new CalibrationMap(\n            [{Floats(map.Raw)}],\n            [{Floats(map.Probability)}])";
    }
}
